import { ITableItem } from '../../redux/types/types';

export const tableList = [
  'id',
  'Производство',
  'Цех',
  'Участок',
  'Этаж',
  'Комната',
  'Дата',
  'Время Реагирования',
  'Работник ФИО',
  'кол-во бутылей',

];

export const tableItems: ITableItem[] = [
  {
    id: 1,
    production: 'Продукт',
    shop: 'Цеп',
    plot: 'd',
    floor: 3,
    room: 'Кладовая',
    date: '22/11/2023',
    responseTime: '05:26',
    employeeName: 'Александр',
    count: 3,
  },
  {
    id: 2,
    production: 'Пee',
    shop: 'Ц',
    plot: 'd',
    floor: 3,
    room: 'Кладовая',
    date: 'Dte',
    responseTime: '05:26',
    employeeName: 'Александр',
    count: 3,
  },
  {
    id: 3,
    production: 'Пee',
    shop: 'Ц',
    plot: 'd',
    floor: 3,
    room: 'Кладовая',
    date: 'Dte',
    responseTime: '05:26',
    employeeName: 'Александр',
    count: 3,
  },
  {
    id: 4,
    production: 'Пee',
    shop: 'Ц',
    plot: 'd',
    floor: 3,
    room: 'Кладовая',
    date: 'Dte',
    responseTime: '05:26',
    employeeName: 'Александр',
    count: 3,
  },
  {
    id: 5,
    production: 'weww',
    shop: 'h',
    plot: 'qwd2qg',
    floor: 5,
    room: 'rer',
    date: 'Dte',
    responseTime: '05:26',
    employeeName: 'Павел',
    count: 3,
  },
];
